reduce external dependencies via mise, remove 1 required env var by using bws
Signed-off-by: Sanyam Kapoor <www@sanyamkapoor.com>

diff --git a/.mise/tasks/deploy b/.mise/tasks/deploy
--- a/.mise/tasks/deploy
+++ b/.mise/tasks/deploy
@@ -20,6 +20,14 @@ if [[ -f .env ]]; then
     set +a
 fi
 
+if [[ -n "${BWS_ACCESS_TOKEN}" ]]; then
+    # shellcheck disable=SC2155
+    export BWS_ORG_ID=$(bws project list | jq -r '.[0].organizationId')
+else
+    echo "[ERROR] Missing BWS_ACCESS_TOKEN."
+    exit 1
+fi
+
 if [[ -z "${usage_inventory}" ]]; then
     echo "[ERROR] Missing inventory."
     exit 1
